name: we_chat
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.10.0
  google_sign_in: ^6.1.5
  cloud_firestore: ^4.9.2
  firebase_storage: ^11.2.7
  flutter_form_builder: ^7.7.0
  form_builder_validators: ^8.1.2
  font_awesome_flutter: ^10.4.0
  image_picker: ^1.0.4
  image_cropper: ^4.0.1
  uuid: ^4.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter


# These all line those in between curly bracket for icon change of app
# {
#   flutter_launcher_icons: "^0.13.1"

# flutter_launcher_icons:
#   android: "ic_launcher"
#   ios: true
#   image_path: "asset/image/chat.png"
#   min_sdk_android: 21 # android min sdk min:16, default 21
# }
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/image/
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
